/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Nov  5 18:16:25 2019. */

#include "ble_message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t BLEmessage_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, BLEmessage, header, header, &Header_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, BLEmessage, payload, header, &Payload_fields),
    PB_LAST_FIELD
};

const pb_field_t Header_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Header, msg_type, msg_type, 0),
    PB_LAST_FIELD
};

const pb_field_t Payload_fields[7] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, Payload, auth_ticket, auth_ticket, &AuthenticationTicket_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, Payload, nonce_exc_msg, auth_ticket, &NonceExchangeMessage_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, Payload, drivers_info_msg, nonce_exc_msg, &DriversInfoMessage_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, Payload, response, drivers_info_msg, &MessageResponse_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, Payload, request, response, &MessageRequest_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, Payload, error_msg, request, &ErrorMessage_fields),
    PB_LAST_FIELD
};

const pb_field_t MessageRequest_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, MessageRequest, target_uuid, target_uuid, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, MessageRequest, action, target_uuid, 0),
    PB_LAST_FIELD
};

const pb_field_t MessageResponse_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, MessageResponse, target_uuid, target_uuid, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, MessageResponse, response, target_uuid, 0),
    PB_LAST_FIELD
};

const pb_field_t AuthenticationTicket_fields[5] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, AuthenticationTicket, secret, secret, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, AuthenticationTicket, pub, secret, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, CALLBACK, OTHER, AuthenticationTicket, signature, pub, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, CALLBACK, OTHER, AuthenticationTicket, auth_nonce, signature, 0),
    PB_LAST_FIELD
};

const pb_field_t NonceExchangeMessage_fields[3] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, NonceExchangeMessage, enc_nonce, enc_nonce, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, CALLBACK, OTHER, NonceExchangeMessage, clear_nonce, enc_nonce, 0),
    PB_LAST_FIELD
};

const pb_field_t ErrorMessage_fields[3] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, ErrorMessage, error_code, error_code, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, ErrorMessage, error_description, error_code, 0),
    PB_LAST_FIELD
};

const pb_field_t DriversInfoMessage_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, DriversInfoMessage, driver_info, driver_info, &DriverInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t DriverInfo_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, DriverInfo, api_description, api_description, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, DriverInfo, public_key, api_description, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, CALLBACK, OTHER, DriverInfo, a3c_dd_uuid, public_key, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(BLEmessage, header) < 65536 && pb_membersize(BLEmessage, payload) < 65536 && pb_membersize(Payload, auth_ticket) < 65536 && pb_membersize(Payload, nonce_exc_msg) < 65536 && pb_membersize(Payload, drivers_info_msg) < 65536 && pb_membersize(Payload, response) < 65536 && pb_membersize(Payload, request) < 65536 && pb_membersize(Payload, error_msg) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_BLEmessage_Header_Payload_MessageRequest_MessageResponse_AuthenticationTicket_NonceExchangeMessage_ErrorMessage_DriversInfoMessage_DriverInfo)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(BLEmessage, header) < 256 && pb_membersize(BLEmessage, payload) < 256 && pb_membersize(Payload, auth_ticket) < 256 && pb_membersize(Payload, nonce_exc_msg) < 256 && pb_membersize(Payload, drivers_info_msg) < 256 && pb_membersize(Payload, response) < 256 && pb_membersize(Payload, request) < 256 && pb_membersize(Payload, error_msg) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_BLEmessage_Header_Payload_MessageRequest_MessageResponse_AuthenticationTicket_NonceExchangeMessage_ErrorMessage_DriversInfoMessage_DriverInfo)
#endif


/* @@protoc_insertion_point(eof) */
