# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ble_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ble_message.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x62le_message.proto\"@\n\nBLEmessage\x12\x17\n\x06header\x18\x01 \x02(\x0b\x32\x07.Header\x12\x19\n\x07payload\x18\x02 \x02(\x0b\x32\x08.Payload\"\x81\x01\n\x06Header\x12%\n\x08msg_type\x18\x01 \x02(\x0e\x32\x13.Header.MessageType\"P\n\x0bMessageType\x12\x0e\n\nAuthTicket\x10\x01\x12\x17\n\x13\x44\x65viceAccessRequest\x10\x02\x12\x18\n\x14\x44\x65viceAccessResponse\x10\x03\"\x90\x01\n\x07Payload\x12,\n\x0b\x61uth_ticket\x18\x01 \x01(\x0b\x32\x15.AuthenticationTicketH\x00\x12\"\n\x07msg_req\x18\x02 \x01(\x0b\x32\x0f.MessageRequestH\x00\x12#\n\x07msg_res\x18\x03 \x01(\x0b\x32\x10.MessageResponseH\x00\x42\x0e\n\x0cpayload_type\"5\n\x0eMessageRequest\x12\x13\n\x0btarget_uuid\x18\x01 \x02(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x02(\t\"8\n\x0fMessageResponse\x12\x13\n\x0btarget_uuid\x18\x01 \x02(\t\x12\x10\n\x08response\x18\x02 \x02(\t\"^\n\x14\x41uthenticationTicket\x12\x0f\n\x07private\x18\x01 \x02(\x0c\x12\x0e\n\x06public\x18\x02 \x02(\x0c\x12\x11\n\tsignature\x18\x03 \x02(\x0c\x12\x12\n\nauth_nonce\x18\x04 \x01(\x0c')
)



_HEADER_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='Header.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AuthTicket', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DeviceAccessRequest', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DeviceAccessResponse', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=137,
  serialized_end=217,
)
_sym_db.RegisterEnumDescriptor(_HEADER_MESSAGETYPE)


_BLEMESSAGE = _descriptor.Descriptor(
  name='BLEmessage',
  full_name='BLEmessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='BLEmessage.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='BLEmessage.payload', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=85,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='Header.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HEADER_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=217,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth_ticket', full_name='Payload.auth_ticket', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_req', full_name='Payload.msg_req', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_res', full_name='Payload.msg_res', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload_type', full_name='Payload.payload_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=220,
  serialized_end=364,
)


_MESSAGEREQUEST = _descriptor.Descriptor(
  name='MessageRequest',
  full_name='MessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_uuid', full_name='MessageRequest.target_uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='MessageRequest.action', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=419,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_uuid', full_name='MessageResponse.target_uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='MessageResponse.response', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=477,
)


_AUTHENTICATIONTICKET = _descriptor.Descriptor(
  name='AuthenticationTicket',
  full_name='AuthenticationTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='private', full_name='AuthenticationTicket.private', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='public', full_name='AuthenticationTicket.public', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='AuthenticationTicket.signature', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_nonce', full_name='AuthenticationTicket.auth_nonce', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=573,
)

_BLEMESSAGE.fields_by_name['header'].message_type = _HEADER
_BLEMESSAGE.fields_by_name['payload'].message_type = _PAYLOAD
_HEADER.fields_by_name['msg_type'].enum_type = _HEADER_MESSAGETYPE
_HEADER_MESSAGETYPE.containing_type = _HEADER
_PAYLOAD.fields_by_name['auth_ticket'].message_type = _AUTHENTICATIONTICKET
_PAYLOAD.fields_by_name['msg_req'].message_type = _MESSAGEREQUEST
_PAYLOAD.fields_by_name['msg_res'].message_type = _MESSAGERESPONSE
_PAYLOAD.oneofs_by_name['payload_type'].fields.append(
  _PAYLOAD.fields_by_name['auth_ticket'])
_PAYLOAD.fields_by_name['auth_ticket'].containing_oneof = _PAYLOAD.oneofs_by_name['payload_type']
_PAYLOAD.oneofs_by_name['payload_type'].fields.append(
  _PAYLOAD.fields_by_name['msg_req'])
_PAYLOAD.fields_by_name['msg_req'].containing_oneof = _PAYLOAD.oneofs_by_name['payload_type']
_PAYLOAD.oneofs_by_name['payload_type'].fields.append(
  _PAYLOAD.fields_by_name['msg_res'])
_PAYLOAD.fields_by_name['msg_res'].containing_oneof = _PAYLOAD.oneofs_by_name['payload_type']
DESCRIPTOR.message_types_by_name['BLEmessage'] = _BLEMESSAGE
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
DESCRIPTOR.message_types_by_name['MessageRequest'] = _MESSAGEREQUEST
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
DESCRIPTOR.message_types_by_name['AuthenticationTicket'] = _AUTHENTICATIONTICKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BLEmessage = _reflection.GeneratedProtocolMessageType('BLEmessage', (_message.Message,), dict(
  DESCRIPTOR = _BLEMESSAGE,
  __module__ = 'ble_message_pb2'
  # @@protoc_insertion_point(class_scope:BLEmessage)
  ))
_sym_db.RegisterMessage(BLEmessage)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'ble_message_pb2'
  # @@protoc_insertion_point(class_scope:Header)
  ))
_sym_db.RegisterMessage(Header)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'ble_message_pb2'
  # @@protoc_insertion_point(class_scope:Payload)
  ))
_sym_db.RegisterMessage(Payload)

MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEREQUEST,
  __module__ = 'ble_message_pb2'
  # @@protoc_insertion_point(class_scope:MessageRequest)
  ))
_sym_db.RegisterMessage(MessageRequest)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGERESPONSE,
  __module__ = 'ble_message_pb2'
  # @@protoc_insertion_point(class_scope:MessageResponse)
  ))
_sym_db.RegisterMessage(MessageResponse)

AuthenticationTicket = _reflection.GeneratedProtocolMessageType('AuthenticationTicket', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATIONTICKET,
  __module__ = 'ble_message_pb2'
  # @@protoc_insertion_point(class_scope:AuthenticationTicket)
  ))
_sym_db.RegisterMessage(AuthenticationTicket)


# @@protoc_insertion_point(module_scope)
