/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Fri Sep  6 16:30:39 2019. */

#ifndef PB_BLE_MESSAGE_PB_H_INCLUDED
#define PB_BLE_MESSAGE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _TestMessage {
    int32_t test_number;
/* @@protoc_insertion_point(struct:TestMessage) */
} TestMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define TestMessage_init_default                 {0}
#define TestMessage_init_zero                    {0}

/* Field tags (for use in manual encoding/decoding) */
#define TestMessage_test_number_tag              1

/* Struct field encoding specification for nanopb */
extern const pb_field_t TestMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define TestMessage_size                         11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BLE_MESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif